apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {.Values.namespace.name}
spec:
  replicas: {.Values.replicascount}
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
      - image: {.Values.image.image}:{.Values.image.tag}
        imagePullPolicy: {.Values.imagepullpolicy}
        name: nginx-alpine
